Report 5272751 "lbt Sales Template"
{
    Caption = 'LeBit Sales Template';
    WordLayout = '.\Layouts\lbtSalesTemplate.docx';
    DefaultLayout = Word;

    dataset
    {
        dataitem(Header; "Sales Header")
        {
            CalcFields = "Amount Including VAT", Amount;
            MaxIteration = 10;
            DataItemTableView = sorting("Document Type", "No.") where("Document Type" = CONST(0));
            RequestFilterFields = "No.";

            column(ReportForNavId_2; 2)
            {
            } // Autogenerated by ForNav - Do not delete
            column(ReportForNav_Header; ReportForNavWriteDataItem('Header', Header))
            {
            }
            column(HasDiscount; ForNAVCheckDocumentDiscount.HasDiscount(Header))
            {
                IncludeCaption = false;
            }
            column(SingleVATPct; VATAmountLine.ForNavSingleVATPct())
            {
                IncludeCaption = false;
            }
            column(lbtCompanyAddressLine; CompanyAddressLine)
            {
                IncludeCaption = false;
            }
            column(lbtHeaderText; HeaderText)
            {
                IncludeCaption = false;
            }
            column(lbtFooterText; FooterText)
            {
                IncludeCaption = false;
            }
            dataitem(Line; "Sales Line")
            {
                CalcFields = "lbt Balance";
                DataItemTableView = sorting("Document Type", "Document No.", "Line No.");
                DataItemLink = "Document No." = field("No."), "Document Type" = field("Document Type");

                column(ReportForNavId_3; 3)
                {
                } // Autogenerated by ForNav - Do not delete
                column(ReportForNav_Line; ReportForNavWriteDataItem('Line', Line))
                {
                }
                column(lbtLineText; LineText)
                {
                    IncludeCaption = false;
                }
                trigger OnPreDataItem();
                begin
                    Line.SetView(ReportForNav.OnPreDataItemView('Line', Line));
                end;

                trigger OnAfterGetRecord();
                begin
                    LineText := Line.lbtGetPrintData("lbt Position"::EditorLine, Line."Document Type".AsInteger());
                end;
            }
            dataitem(VATAmountLine; "VAT Amount Line")
            {
                UseTemporary = true;
                DataItemTableView = sorting("VAT Identifier", "VAT Calculation Type", "Tax Group Code", "Use Tax", Positive);

                column(ReportForNavId_1000000001; 1000000001)
                {
                } // Autogenerated by ForNav - Do not delete
                column(ReportForNav_VATAmountLine; ReportForNavWriteDataItem('VATAmountLine', VATAmountLine))
                {
                }
                trigger OnPreDataItem();
                begin
                    if not PrintVATAmountLines then CurrReport.Break;
                    VATAmountLine.SetView(ReportForNav.OnPreDataItemView('VATAmountLine', VATAmountLine, 'Header', Header));
                end;
            }
            dataitem(VATClause; "VAT Clause")
            {
                UseTemporary = true;
                DataItemTableView = sorting(Code);

                column(ReportForNavId_1000000002; 1000000002)
                {
                } // Autogenerated by ForNav - Do not delete
                column(ReportForNav_VATClause; ReportForNavWriteDataItem('VATClause', VATClause))
                {
                }
                trigger OnPreDataItem();
                begin
                    VATClause.SetView(ReportForNav.OnPreDataItemView('VATClause', VATClause, 'Header', Header));
                end;
            }
            dataitem(Integer; Integer)
            {
                DataItemTableView = sorting(Number) where(Number = CONST(1));

                column(ReportForNavId_1000000003; 1000000003)
                {
                } // Autogenerated by ForNav - Do not delete
                column(ReportForNav_Integer; ReportForNavWriteDataItem('Integer', Integer))
                {
                }
                trigger OnPreDataItem();
                begin
                    Integer.SetView(ReportForNav.OnPreDataItemView('Integer', Integer));
                end;
            }
            trigger OnPreDataItem();
            begin
                Header.SetView(ReportForNav.OnPreDataItemView('Header', Header));
            end;
            trigger OnAfterGetRecord();
            begin
                ChangeLanguage("Language Code");
                GetVatAmountLines;
                GetVATClauses;
                HeaderText := Header.lbtGetPrintData("lbt Position"::EditorHeader, Header."Document Type".AsInteger());
                FooterText := Header.lbtGetPrintData("lbt Position"::EditorFooter, Header."Document Type".AsInteger());
            end;
        }
    }
    requestpage
    {
        layout
        {
            area(Content)
            {
                group(Options)
                {
                    Caption = 'Options';

                    field(NoOfCopies; NoOfCopies)
                    {
                        ApplicationArea = All;
                        Caption = 'No. of Copies';
                    }
                }
            }
        }
    }
    trigger OnInitReport()
    begin
        ;
        ReportsForNavInit;
        Codeunit.Run(Codeunit::"ForNAV First Time Setup");
    end;
    trigger OnPreReport()
    var
        lbtFormatDocument: Codeunit "lbt Format Document";
    begin
        CompanyAddressLine := lbtFormatDocument.CompanyAddressLine();
        ReportForNav.SetCopies('Header', NoOfCopies);
        ReportForNav.LoadWatermarkFromSetup(ForNav_WatermarkType::Document);
        ;
        ReportsForNavPre;
    end;

    var
        ForNAVCheckDocumentDiscount: Codeunit "ForNAV Check Document Discount";
        NoOfCopies: Integer;
        CompanyAddressLine: Text;
        HeaderText: Text;
        FooterText: Text;
        LineText: Text;
    local procedure ChangeLanguage(LanguageCode: Code[10])
    var
        ForNAVSetup: Record "ForNAV Setup";
    begin
        ForNAVSetup.Get;
        if ForNAVSetup."Inherit Language Code" then CurrReport.Language(ReportForNav.GetLanguageID(LanguageCode));
    end;
    local procedure GetVatAmountLines()
    var
        ForNAVGetVatAmountLines: Codeunit "ForNAV Get Vat Amount Lines";
    begin
        VATAmountLine.DeleteAll;
        ForNAVGetVatAmountLines.GetVatAmountLines(Header, VATAmountLine);
    end;
    local procedure GetVATClauses()
    var
        ForNAVGetVatClause: Codeunit "ForNAV Get Vat Clause";
    begin
        VATClause.DeleteAll;
        ForNAVGetVatClause.GetVATClauses(VATAmountLine, VATClause, Header."Language Code");
    end;

    local procedure PrintVATAmountLines(): Boolean
    var
        ForNAVSetup: Record "ForNAV Setup";
    begin
        ForNAVSetup.Get;
        case ForNAVSetup."VAT Report Type" of
            ForNAVSetup."vat report type"::Always:
                exit(true);
            ForNAVSetup."vat report type"::"Multiple Lines":
                exit(VATAmountLine.Count > 1);
            ForNAVSetup."vat report type"::Never:
                exit(false);
        end;
    end;

    procedure PrintLogo(ForNAVSetup: Record "ForNAV Setup"): Boolean
    begin
        exit(true);
    end;
    // --> Reports ForNAV Autogenerated code - do not delete or modify
    var
        ReportForNav: Codeunit "ForNAV Report Management";
        ReportForNavTotalsCausedBy: Integer;
        ReportForNavInitialized: Boolean;
        ReportForNavShowOutput: Boolean;
    local procedure ReportsForNavInit()
    var
        id: Integer;
    begin
        Evaluate(id, CopyStr(CurrReport.ObjectId(false), StrPos(CurrReport.ObjectId(false), ' ') + 1));
        ReportForNav.OnInit(id);
    end;

    local procedure ReportsForNavPre()
    begin
    end;
    local procedure ReportForNavSetTotalsCausedBy(value: Integer)
    begin
        ReportForNavTotalsCausedBy := value;
    end;
    local procedure ReportForNavSetShowOutput(value: Boolean)
    begin
        ReportForNavShowOutput := value;
    end;
    local procedure ReportForNavInit(jsonObject: JsonObject)
    begin
        ReportForNav.Init(jsonObject, CurrReport.ObjectId);
    end;

    local procedure ReportForNavWriteDataItem(dataItemId: Text; rec: Variant): Text
    var
        values: Text;
        jsonObject: JsonObject;
        currLanguage: Integer;
    begin
        if not ReportForNavInitialized then begin
            ReportForNavInit(jsonObject);
            ReportForNavInitialized := true;
        end;
        case (dataItemId) of
            'Header':
                begin
                    jsonObject.Add('CurrReport$Language$Integer', CurrReport.Language);
                end;
        end;
        ReportForNav.AddDataItemValues(jsonObject, dataItemId, rec);
        jsonObject.WriteTo(values);
        exit(values);
    end;
    // Reports ForNAV Autogenerated code - do not delete or modify -->
}
